### ISSUE TITLE
Less intrusive autocomplete

### ISSUE THREAD

**Issue by iconara** [atom/autocomplete#11]
Would it be possible to get a less intrusive autocomplete, something more like TextMate's where you press escape to cycle through alternatives.

When I code I almost always know what I want to autocomplete to, I just don't want to type it. Having to select from a list makes me slower, not faster.

At the same time, I know that many like autocomplete with a list and are used to that from other editors, so I'm just asking for a way to run the autocomplete in a less UI-driven manner. If there were actions for autocomplete with next suggestion I could hook up the keymappings myself, but as far as I can tell it's not currently possible, at least I didn't manage to autocomplete without showing the alternatives panel.

**Comment by grahammutter** [comment]
+1 for wanting to be able to disable autocomplete. I love everything about atom but I have to uninstall it. It's too obtrusive to my workflow. Hopefully optional disable is a feature in the next release!

**Comment by 50Wliu** [comment]
@grahammutter could you elaborate a bit please?  I have to press <kbd>Ctrl+Space</kbd> in order to toggle autocomplete.  In addition, if it is always on by default for you somehow, you can always disable this package by going to Settings-->Packages-->autocomplete.

Also, this probably is even more obtrusive, but you may want to take a look at [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) which will be replacing the default autocomplete in the near future.

**Comment by grahammutter** [comment]
Settings-->Packages-->autocomplete only disables my ability to manually call the autocomplete, but it still automatically brings itself up after 95% of keypresses. Perhaps my build is bugged. I'll try clean wiping it and reinstalling.

**Comment by grahammutter** [comment]
I've figured out what was causing it. autocomplete-plus is a dependency for the TypeScript plugin. Though I was uninstalling it, it was being automatically reinstalled on every launch. Disabling keystroke suggestions in the autocomplete-plus plugin but leaving it installed has worked as a fix.

**Comment by cosinekitty** [comment]
+1 on disabling keystroke suggestions.  My reaction was: too visually distracting.  The keystroke suggester is far too aggressive.  I like Visual Studio's more restrained suggestions.  If I'm "dotting into" an object, it's nice to automatically see a list of the properties and functions within it.  The rest of the time, I just want to type.  As a compromise, I'm OK with having to manually press Ctrl+Space when I want help in Atom, to avoid the stress of constantly losing my focus because of visual churn.

**Comment by mnquintana** [comment]
This repo is no longer maintained - Atom's autocomplete functionality is now provided by https://github.com/atom/autocomplete-plus

**Comment by kevinsawicki** [comment]
This package is deprecated and no longer shipped with Atom. If this is still an issue using the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, please open up a new issue on that repository, thanks.
