### ISSUE TITLE
Just STEAL IT FROM brackets

### ISSUE THREAD

**Issue by pjv** [atom/autocomplete#23]
As of now, brackets has (in my opinion) better autocomplete than atom. It's fast, unobtrusive, lightweight, and it seems to be using the syntax file for the language being edited to compile the list of completions which to me is as important as including symbols from the file being edited.

Here is a screenshot of brackets editing in a less file (would be the same in a comparable css file):

![image](https://cloud.githubusercontent.com/assets/327716/2605102/1c01c982-bb41-11e3-8109-f3f1058aa9b6.png)

In use, it feels right and like it is helping me. Autocomplete in atom so far feels clumsy and like it is getting in my way.

**Comment by theseyi** [comment]
+1

**Comment by thedaniel** [comment]
A number of people are working on a replacement / improvement to autocomplete in https://github.com/atom/atom/issues/4364 - this issue is on the [Atom 1.0 feature list](https://github.com/atom/atom/issues/3684), so while we don't plan to adopt code from Brackets, this package will be replaced or changed significantly in ways that should make it behave more like what people commenting on this issue want.

**Comment by spencerthayer** [comment]
+1 _still and issue_

Atom 1.0 brackets autocomplete+ package is just not good enough to justify leaving Brackets or KomodoIDE.

**Comment by thedaniel** [comment]
Feel free to file more specific issues on the autocomplete-plus repository or the repos for the language completions that you find lacking.
